-- Active: 1763074690906@@127.0.0.1@5432@kathy_wool
INSERT INTO categories (name, description) VALUES
('decoracion', 'Art�culos para el hogar y adornos artesanales'),
('amigurumi', 'Figuras tejidas a mano con la t�cnica japonesa amigurumi'),
('blusas', 'Prendas de vestir tejidas y de temporada'),
('navidad', 'Decoraci�n y personajes tem�ticos de �poca navide�a'),
('accesorios', 'Complementos de moda y art�culos de uso personal'),
('figuras', 'Personajes coleccionables y figuras detalladas'),
('pokemon', 'Criaturas y personajes del universo Pok�mon'),
('personajes', 'Figuras inspiradas en cuentos, pel�culas y literatura'),
('sailor moon', 'Colecci�n inspirada en el anime Sailor Moon'),
('videojuegos', 'Personajes ic�nicos del mundo del gaming'),
('bebe', 'Art�culos suaves y seguros para los m�s peque�os');

INSERT INTO products (name, category_id, description, price, stock, url_image) VALUES
('Atrapasue�os', 1, 'Tejido con hilos de serenidad, este atrapasue�os promete filtrar tus noches para que solo queden los deseos m�s dulces.', 4550, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981252/atrapasuenos_iuwyjj.jpg'),
('Axolote', 2, 'Peque�o guardi�n de las aguas mexicanas tejido con amor. Un amigurumi rosado que te acompa�ar� con su sonrisa eterna.', 3200, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981253/axolote_zfzy6o.png'),
('Blusa crochet', 3, 'Elegancia hilada a mano. Combina un patr�n cl�sico con un toque moderno, perfecta para sentirte �nica.', 8990, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981250/blusa_crochet_pnlfur.jpg'),
('Blusa crochet', 3, 'Textura suave y dise�o delicado. Una pieza vers�til tejida punto a punto para adaptarse a tu estilo.', 8500, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981548/blusa_crochet_t29fqt.png'),
('Blusa manga corta', 3, 'Frescura y comodidad en cada puntada. Ideal para tardes de sol, destaca por su dise�o transpirable.', 7820, 6, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981260/blusa_manga_corta_wsj4pc.jpg'),
('Blusa sin mangas', 3, 'Libertad de movimiento con un toque chic. Minimalismo con el alma del tejido tradicional.', 7470, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981254/blusa_sin_mangas_auvumg.jpg'),
('Cascanueces', 4, 'Un cl�sico navide�o reinventado. Aportar� la magia de los cuentos de invierno con sus detalles vibrantes.', 5500, 10, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/cascanueces_nhsz5v.png'),
('Cintillo unicornio', 5, 'Transforma un d�a ordinario en uno m�gico. El accesorio perfecto para dejar volar la imaginaci�n.', 1530, 12, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981253/cintillo_unicornio_f2smxx.jpg'),
('Conejo', 2, 'Orejas largas y coraz�n grande. Ideal para los m�s peque�os o para decorar un rinc�n especial.', 2800, 7, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981254/conejo_d9rozg.jpg'),
('Decoraci�n mesa', 1, 'Viste tu mesa con distinci�n. Piezas artesanales que convierten una cena com�n en un evento memorable.', 4215, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981256/decoracion_mesa_znnrat.jpg'),
('Duende navidad', 4, 'Tra�do directamente desde el taller del Polo Norte. Llenar� tu hogar de alegr�a y fantas�a.', 3890, 8, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981255/duende_navidad_kbmqup.jpg'),
('Elvis', 6, '�El Rey ha vuelto en formato amigurumi! La pieza de colecci�n definitiva para amantes del Rock & Roll.', 6000, 1, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981546/elvis_xo0w7n.png'),
('Foca', 2, 'Redondita, suave y lista para abrazar. Trae consigo la calma del oc�ano y la dulzura de lo hecho a mano.', 2450, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981544/foca_rojpzi.png'),
('Gato blanco', 2, 'Un minino que no suelta pelo pero s� mucho cari�o. El regalo perfecto para cualquier cat lover.', 2999, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981255/gato_blanco_w7tlj2.jpg'),
('Gato sombrero', 2, 'Elegancia felina con un toque de misterio. Derrocha personalidad y destaca en cualquier estanter�a.', 3420, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/gato_sombrero_c1hm60.png'),
('Gengar', 7, '�Cuidado con las sombras! Captura toda la esencia del Pok�mon tipo fantasma en versi�n abrazable.', 4000, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981258/gengar_lyo9bz.jpg'),
('Gorro monito del monte', 5, 'Inspirado en nuestra fauna nativa. Un gorrito tierno y abrigador para los m�s peque�os.', 2280, 6, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981258/gorro_monito_del_monte_kovu7o.png'),
('Lenore', 8, 'Para amantes de lo g�tico y lo tierno. La ni�a muerta tejida con cada detalle de su oscuro encanto.', 4850, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981259/lenore_vwezc9.jpg'),
('Mangas crochet', 5, 'El complemento ideal para outfits de entretiempo. A�aden textura y arte a cualquier look b�sico.', 3500, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/mangas_crochet_ea0j4f.jpg'),
('Mu�eco de nieve', 4, 'Un amiguito de nieve que nunca se derrite. El centro de tus decoraciones invernales.', 2740, 9, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772985414/muneco_de_nieve_osvwrv.jpg'),
('Personajes navidad', 4, 'El esp�ritu navide�o en un set de figuras tejidas. Ideales para un rinc�n festivo lleno de calidez.', 6500, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981549/personajes_navidad_y8wbbh.png'),
('Pikachu', 7, '�Pika-Pika! El compa�ero m�s fiel de los entrenadores Pok�mon en versi�n de crochet radiante.', 4110, 7, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/pikachu_o2tszq.jpg'),
('Principito con zorro', 8, 'Lo esencial es invisible a los ojos. Un recordatorio tangible de la amistad y la pureza.', 5800, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981263/principito_con_zorro_gp4uev.jpg'),
('Rana', 2, 'Salta de la charca a tus brazos. Una ranita verde tejida que iluminar� cualquier espacio.', 1990, 11, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981264/rana_gtaksz.jpg'),
('Sailor Mars', 9, 'El poder de Marte en tus manos. Con su uniforme ic�nico y esp�ritu valiente para los fans del anime.', 5230, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/sailor_mars_d1vuab.jpg'),
('Sailor Moon', 9, '�Por el poder del Prisma Lunar! Defensora del amor y la justicia en una versi�n artesanal m�gica.', 5500, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981264/sailor_moon_lkjfgp.jpg'),
('Sailor Moon personajes', 9, 'Colecci�n completa de las Scouts. Formando un set estelar lleno de nostalgia y arte.', 9500, 1, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981267/sailor_moon_personajes_clhmkl.jpg'),
('Sailor Venus', 9, 'La guerrera del amor y la belleza. Con su lazo caracter�stico, es la pieza que falta en tu colecci�n.', 5230, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/sailor_venus_pvgdpv.jpg'),
('Shadow', 10, 'La forma de vida definitiva, ahora en hilo. Shadow luce su actitud seria y detalles en rojo.', 4460, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981267/shadow_o5d7zj.png'),
('Sonajero', 11, 'El primer amigo de tu beb�. Estimula los sentidos con texturas suaves y sonidos delicados.', 1850, 15, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981546/sonajero_klg7cd.png'),
('Tinkerbell', 8, 'Un poco de polvo de hadas y mucho crochet. Lista para traerte la magia de Nunca Jam�s.', 4999, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/tinkerbell_p3yqbm.jpg'),
('Unicornio', 2, 'Crines de arco�ris y un cuerno lleno de sue�os. Una criatura fant�stica que llenar� de color tu hogar.', 3675, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/unicornio_kn6kxp.jpg'),
('Zelda', 10, 'La sabidur�a de Hyrule personificada. Un tributo perfecto con ropajes reales detallados en hilo.', 6200, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/zelda_jkpdfb.jpg');