INSERT INTO categories (name, description) VALUES
('decoracion', 'Artículos para el hogar y adornos artesanales'),
('amigurumi', 'Figuras tejidas a mano con la técnica japonesa amigurumi'),
('blusas', 'Prendas de vestir tejidas y de temporada'),
('navidad', 'Decoración y personajes temáticos de época navideña'),
('accesorios', 'Complementos de moda y artículos de uso personal'),
('figuras', 'Personajes coleccionables y figuras detalladas'),
('pokemon', 'Criaturas y personajes del universo Pokémon'),
('personajes', 'Figuras inspiradas en cuentos, películas y literatura'),
('sailor moon', 'Colección inspirada en el anime Sailor Moon'),
('videojuegos', 'Personajes icónicos del mundo del gaming'),
('bebe', 'Artículos suaves y seguros para los más pequeños');

INSERT INTO products (name, category_id, description, price, stock, url_image) VALUES
('Atrapasueños', 1, 'Tejido con hilos de serenidad, este atrapasueños promete filtrar tus noches para que solo queden los deseos más dulces.', 4550, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981252/atrapasuenos_iuwyjj.jpg'),
('Axolote', 2, 'Pequeño guardián de las aguas mexicanas tejido con amor. Un amigurumi rosado que te acompañará con su sonrisa eterna.', 3200, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981253/axolote_zfzy6o.png'),
('Blusa crochet', 3, 'Elegancia hilada a mano. Combina un patrón clásico con un toque moderno, perfecta para sentirte única.', 8990, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981250/blusa_crochet_pnlfur.jpg'),
('Blusa crochet', 3, 'Textura suave y diseño delicado. Una pieza versátil tejida punto a punto para adaptarse a tu estilo.', 8500, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981548/blusa_crochet_t29fqt.png'),
('Blusa manga corta', 3, 'Frescura y comodidad en cada puntada. Ideal para tardes de sol, destaca por su diseño transpirable.', 7820, 6, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981260/blusa_manga_corta_wsj4pc.jpg'),
('Blusa sin mangas', 3, 'Libertad de movimiento con un toque chic. Minimalismo con el alma del tejido tradicional.', 7470, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981254/blusa_sin_mangas_auvumg.jpg'),
('Cascanueces', 4, 'Un clásico navideño reinventado. Aportará la magia de los cuentos de invierno con sus detalles vibrantes.', 5500, 10, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/cascanueces_nhsz5v.png'),
('Cintillo unicornio', 5, 'Transforma un día ordinario en uno mágico. El accesorio perfecto para dejar volar la imaginación.', 1530, 12, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981253/cintillo_unicornio_f2smxx.jpg'),
('Conejo', 2, 'Orejas largas y corazón grande. Ideal para los más pequeños o para decorar un rincón especial.', 2800, 7, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981254/conejo_d9rozg.jpg'),
('Decoración mesa', 1, 'Viste tu mesa con distinción. Piezas artesanales que convierten una cena común en un evento memorable.', 4215, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981256/decoracion_mesa_znnrat.jpg'),
('Duende navidad', 4, 'Traído directamente desde el taller del Polo Norte. Llenará tu hogar de alegría y fantasía.', 3890, 8, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981255/duende_navidad_kbmqup.jpg'),
('Elvis', 6, '¡El Rey ha vuelto en formato amigurumi! La pieza de colección definitiva para amantes del Rock & Roll.', 6000, 1, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981546/elvis_xo0w7n.png'),
('Foca', 2, 'Redondita, suave y lista para abrazar. Trae consigo la calma del océano y la dulzura de lo hecho a mano.', 2450, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981544/foca_rojpzi.png'),
('Gato blanco', 2, 'Un minino que no suelta pelo pero sí mucho cariño. El regalo perfecto para cualquier cat lover.', 2999, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981255/gato_blanco_w7tlj2.jpg'),
('Gato sombrero', 2, 'Elegancia felina con un toque de misterio. Derrocha personalidad y destaca en cualquier estantería.', 3420, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/gato_sombrero_c1hm60.png'),
('Gengar', 7, '¡Cuidado con las sombras! Captura toda la esencia del Pokémon tipo fantasma en versión abrazable.', 4000, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981258/gengar_lyo9bz.jpg'),
('Gorro monito del monte', 5, 'Inspirado en nuestra fauna nativa. Un gorrito tierno y abrigador para los más pequeños.', 2280, 6, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981258/gorro_monito_del_monte_kovu7o.png'),
('Lenore', 8, 'Para amantes de lo gótico y lo tierno. La niña muerta tejida con cada detalle de su oscuro encanto.', 4850, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981259/lenore_vwezc9.jpg'),
('Mangas crochet', 5, 'El complemento ideal para outfits de entretiempo. Añaden textura y arte a cualquier look básico.', 3500, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/mangas_crochet_ea0j4f.jpg'),
('Muñeco de nieve', 4, 'Un amiguito de nieve que nunca se derrite. El centro de tus decoraciones invernales.', 2740, 9, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772985414/muneco_de_nieve_osvwrv.jpg'),
('Personajes navidad', 4, 'El espíritu navideño en un set de figuras tejidas. Ideales para un rincón festivo lleno de calidez.', 6500, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981549/personajes_navidad_y8wbbh.png'),
('Pikachu', 7, '¡Pika-Pika! El compañero más fiel de los entrenadores Pokémon en versión de crochet radiante.', 4110, 7, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981261/pikachu_o2tszq.jpg'),
('Principito con zorro', 8, 'Lo esencial es invisible a los ojos. Un recordatorio tangible de la amistad y la pureza.', 5800, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981263/principito_con_zorro_gp4uev.jpg'),
('Rana', 2, 'Salta de la charca a tus brazos. Una ranita verde tejida que iluminará cualquier espacio.', 1990, 11, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981264/rana_gtaksz.jpg'),
('Sailor Mars', 9, 'El poder de Marte en tus manos. Con su uniforme icónico y espíritu valiente para los fans del anime.', 5230, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/sailor_mars_d1vuab.jpg'),
('Sailor Moon', 9, '¡Por el poder del Prisma Lunar! Defensora del amor y la justicia en una versión artesanal mágica.', 5500, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981264/sailor_moon_lkjfgp.jpg'),
('Sailor Moon personajes', 9, 'Colección completa de las Scouts. Formando un set estelar lleno de nostalgia y arte.', 9500, 1, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981267/sailor_moon_personajes_clhmkl.jpg'),
('Sailor Venus', 9, 'La guerrera del amor y la belleza. Con su lazo característico, es la pieza que falta en tu colección.', 5230, 4, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/sailor_venus_pvgdpv.jpg'),
('Shadow', 10, 'La forma de vida definitiva, ahora en hilo. Shadow luce su actitud seria y detalles en rojo.', 4460, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981267/shadow_o5d7zj.png'),
('Sonajero', 11, 'El primer amigo de tu bebé. Estimula los sentidos con texturas suaves y sonidos delicados.', 1850, 15, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981546/sonajero_klg7cd.png'),
('Tinkerbell', 8, 'Un poco de polvo de hadas y mucho crochet. Lista para traerte la magia de Nunca Jamás.', 4999, 3, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/tinkerbell_p3yqbm.jpg'),
('Unicornio', 2, 'Crines de arcoíris y un cuerno lleno de sueños. Una criatura fantástica que llenará de color tu hogar.', 3675, 5, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981268/unicornio_kn6kxp.jpg'),
('Zelda', 10, 'La sabiduría de Hyrule personificada. Un tributo perfecto con ropajes reales detallados en hilo.', 6200, 2, 'https://res.cloudinary.com/dorfpavlv/image/upload/v1772981269/zelda_jkpdfb.jpg');